force-app/main/default/objects/Trailblazer__c/Trailblazer__c.object-meta.xml
<CustomObject>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/AvatarUrl__c.field-meta.xml
<CustomField>
    <fullName>AvatarUrl__c</fullName>
    <label>Avatar URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <label>Badges</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/ProfileUrl__c.field-meta.xml
<CustomField>
    <fullName>ProfileUrl__c</fullName>
    <label>Profile URL</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scout</fullName>
            </value>
            <value>
                <fullName>Hiker</fullName>
            </value>
            <value>
                <fullName>Explorer</fullName>
            </value>
            <value>
                <fullName>Adventurer</fullName>
            </value>
            <value>
                <fullName>Mountaineer</fullName>
            </value>
            <value>
                <fullName>Expeditioner</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrailblazersReptile.cls
public with sharing class TrailblazersReptile implements Queueable, Database.AllowsCallouts {
    private string trailblazerId;
    
    public TrailblazersReptile(String trailblazerId) {
        this.trailblazerId = trailblazerId;
    }

    public void execute(QueueableContext qc) {
        Trailblazer__c trailblazer = [SELECT Id, ProfileUrl__c FROM TrailBlazer__c WHERE Id = :trailblazerId LIMIT 1];
        HttpRequest request = new HttpRequest();
        request.setEndpoint(trailblazer.ProfileUrl__c);
        request.setMethod('GET');
        HttpResponse response = (new Http()).send(request);
        String dataStr = response.getBody();
        String avatarUrl = dataStr.substringBetween('class="user-information__avatar-img" src="', '" alt="');
        String badgeCount = dataStr.substringBetween('data-test-badges-count>', '</div>');
        String points = dataStr.substringBetween('data-test-points-count>\n', '\n</div>').remove(',');
        String rank = dataStr.substringBetween('/assets/ranks/', '-');

        trailblazer.AvatarUrl__c = avatarUrl;
        trailblazer.Badges__c = Integer.valueOf(badgeCount);
        trailblazer.Points__c = Integer.valueOf(points);
        trailblazer.Rank__c = rank;

        update trailblazer;
    }
}