force-app/main/default/objects/Trailblazer__c/Trailblazer__c.object-meta.xml
<CustomObject>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <label>Badges</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/BadgesData__c.field-meta.xml
<CustomField>
    <fullName>BadgesData__c</fullName>
    <label>BadgesData</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/BadgesLastMonth__c.field-meta.xml
<CustomField>
    <fullName>BadgesLastMonth__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Badges Last Month</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/PointsData__c.field-meta.xml
<CustomField>
    <fullName>PointsData__c</fullName>
    <label>Points Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/PointsLastMonth__c.field-meta.xml
<CustomField>
    <fullName>PointsLastMonth__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Last Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scout</fullName>
            </value>
            <value>
                <fullName>Hiker</fullName>
            </value>
            <value>
                <fullName>Explorer</fullName>
            </value>
            <value>
                <fullName>Adventurer</fullName>
            </value>
            <value>
                <fullName>Mountaineer</fullName>
            </value>
            <value>
                <fullName>Expeditioner</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/RankLastMonth__c.field-meta.xml
<CustomField>
    <fullName>RankLastMonth__c</fullName>
    <label>Rank Last Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrailblazerDataArchiveScheduler.cls
/**
 * System.Schedule('Trailblazer Data Archive Job', '0 0 01 1 * ? *', new TrailblazerDataArchiveScheduler());
 * Runs at the 1st day of every month
 */
public without sharing class TrailblazerDataArchiveScheduler implements Schedulable {
    public TrailblazerDataArchiveScheduler() {
    }

    public void execute(SchedulableContext sc) {
        List<Trailblazer__c> trailblazers = new List<Trailblazer__c>();
        Date lastDayOfLastMonth = Date.today().addDays(-1);

        for (Trailblazer__c trailblazer : [
            SELECT Points__c, Badges__c, PointsData__c, BadgesData__c, Rank__c
            FROM Trailblazer__c
        ]) {
            try {
                trailblazer.PointsLastMonth__c = trailblazer.Points__c;
                trailblazer.BadgesLastMonth__c = trailblazer.Badges__c;
                trailblazer.RankLastMonth__c = trailblazer.Rank__c;

                // put last month points to PointsData__c
                List<ArchiveData> oldPointsData = String.isBlank(trailblazer.PointsData__c)
                    ? new List<ArchiveData>()
                    : (List<ArchiveData>) JSON.deserialize(
                          trailblazer.PointsData__c,
                          List<ArchiveData>.class
                      );

                oldPointsData.add(
                    new ArchiveData(lastDayOfLastMonth, trailblazer.PointsLastMonth__c)
                );
                trailblazer.PointsData__c = JSON.serialize(oldPointsData);

                // put last month badges to BadgesData__c
                List<ArchiveData> oldBadgesData = String.isBlank(trailblazer.BadgesData__c)
                    ? new List<ArchiveData>()
                    : (List<ArchiveData>) JSON.deserialize(
                          trailblazer.BadgesData__c,
                          List<ArchiveData>.class
                      );

                oldBadgesData.add(
                    new ArchiveData(lastDayOfLastMonth, trailblazer.BadgesLastMonth__c)
                );
                trailblazer.BadgesData__c = JSON.serialize(oldBadgesData);

                trailblazers.add(trailblazer);
            } catch (Exception ex) {
                insert new Log__c(
                    ApexCodeName__c = 'TrailblazerDataArchiveScheduler',
                    Data__c = ex.getMessage() + '------' + ex.getLineNumber()
                );
            }
        }

        update trailblazers;
    }
    private class ArchiveData {
        public ArchiveData(Date dataDate, Decimal count) {
            this.dataDate = dataDate;
            this.count = count;
        }

        public Date dataDate { get; set; }
        public Decimal count { get; set; }
    }
}