force-app/main/default/objects/Trailblazer__c/Trailblazer__c.object-meta.xml
<CustomObject>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <label>Badges</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/BadgesLastMonth__c.field-meta.xml
<CustomField>
    <fullName>BadgesLastMonth__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Badges Last Month</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/CertificationCount__c.field-meta.xml
<CustomField>
    <fullName>CertificationCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Certification Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/IsCharketEmployee__c.field-meta.xml
<CustomField>
    <fullName>IsCharketEmployee__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Charket Employee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/NewBadges__c.field-meta.xml
<CustomField>
    <fullName>NewBadges__c</fullName>
    <formula>Badges__c -  BadgesLastMonth__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>New Badges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/NewPoints__c.field-meta.xml
<CustomField>
    <fullName>NewPoints__c</fullName>
    <formula>Points__c -  PointsLastMonth__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>New Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/PointsLastMonth__c.field-meta.xml
<CustomField>
    <fullName>PointsLastMonth__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Points Last Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/ProfileUrl__c.field-meta.xml
<CustomField>
    <fullName>ProfileUrl__c</fullName>
    <label>Profile URL</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scout</fullName>
            </value>
            <value>
                <fullName>Hiker</fullName>
            </value>
            <value>
                <fullName>Explorer</fullName>
            </value>
            <value>
                <fullName>Adventurer</fullName>
            </value>
            <value>
                <fullName>Mountaineer</fullName>
            </value>
            <value>
                <fullName>Expeditioner</fullName>
            </value>
            <value>
                <fullName>Ranger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/RankLastMonth__c.field-meta.xml
<CustomField>
    <fullName>RankLastMonth__c</fullName>
    <label>Rank Last Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrailheadRestApi.cls
@RestResource(urlMapping='/trailhead/*')
global without sharing class TrailheadRestApi {
    @HttpPost
    global static void doPost() {
        try {
            String param = RestContext.request.params.get('text');

            String result;

            if (param == 'points' || param == 'p') {
                result = getPointRanks();
            } else if (param == 'badges' || param == 'b') {
                result = getBadgeRanks();
            } else if (param == 'last month' || param == 'l') {
                result = getLastMonthRanks();
            } else if (param == 'all' || param == 'a') {
                result = getMonthRanks();
            } else {
                result = getBadgeRanks();
            }

            RestContext.response.statusCode = 200;
            RestContext.response.responseBody = Blob.valueOf(result);
        } catch (Exception ex) {
        }
    }

    private static String getPointRanks() {
        return formats(
            [
                SELECT
                    ProfileUrl__c,
                    Name,
                    Points__c,
                    Rank__c,
                    Badges__c,
                    NewPoints__c,
                    CertificationCount__c,
                    NewBadges__c
                FROM Trailblazer__c
                WHERE IsCharketEmployee__c = TRUE AND NewPoints__c > 0
                ORDER BY NewPoints__c DESC, NewBadges__c DESC
            ]
        );
    }

    private static String getBadgeRanks() {
        return formats(
            [
                SELECT
                    ProfileUrl__c,
                    Name,
                    Points__c,
                    Rank__c,
                    Badges__c,
                    NewPoints__c,
                    CertificationCount__c,
                    NewBadges__c
                FROM Trailblazer__c
                WHERE IsCharketEmployee__c = TRUE AND NewBadges__c > 0
                ORDER BY NewBadges__c DESC, NewPoints__c DESC
            ]
        );
    }

    private static String getMonthRanks() {
        return formats(
            [
                SELECT
                    ProfileUrl__c,
                    Name,
                    Points__c,
                    Rank__c,
                    Badges__c,
                    NewPoints__c,
                    CertificationCount__c,
                    NewBadges__c
                FROM Trailblazer__c
                WHERE IsCharketEmployee__c = TRUE
                ORDER BY Name
            ]
        );
    }

    private static String getLastMonthRanks() {
        List<Trailblazer> trailblazers = new List<Trailblazer>();

        for (Trailblazer__c t : [
            SELECT Id, Name, RankLastMonth__c, BadgesLastMonth__c, PointsLastMonth__c
            FROM Trailblazer__c
            WHERE IsCharketEmployee__c = TRUE
            ORDER BY Name
        ]) {
            trailblazers.add(new Trailblazer(t));
        }

        return JSON.serialize(trailblazers);
    }

    private static String formats(List<Trailblazer__c> trailblazers) {
        String result = '';
        Integer totalBadges = 0;
        Integer totalPoints = 0;

        for (Trailblazer__c trailblazer : trailblazers) {
            result += format(trailblazer, trailblazers.indexOf(trailblazer));
            totalBadges += (Integer) trailblazer.NewBadges__c;
            totalPoints += (Integer) trailblazer.NewPoints__c;
        }

        result +=
            '\nTotal Count: ' +
            trailblazers.size() +
            '\n' +
            'Total Badges: ' +
            totalBadges +
            '\n' +
            'Total Points: ' +
            totalPoints;

        return result;
    }

    private static String format(Trailblazer__c trailblazer, Integer index) {
        return (index + 1) +
            '. Points: `' +
            trailblazer.Points__c +
            '` Badges: `' +
            trailblazer.Badges__c +
            '` New Points: `' +
            (Integer) trailblazer.NewPoints__c +
            '` New Badges: `' +
            (Integer) trailblazer.NewBadges__c +
            '` Rank: `' +
            trailblazer.Rank__c +
            '` Certs: `' +
            trailblazer.CertificationCount__c +
            '` Name: <' +
            trailblazer.ProfileUrl__c +
            '|' +
            trailblazer.Name +
            '>\n\n';
    }

    private class Trailblazer {
        private Trailblazer(Trailblazer__c t) {
            this.name = t.Name;
            this.rankLastMonth = t.RankLastMonth__c;
            this.badgesLastMonth = (Integer) t.BadgesLastMonth__c;
            this.pointsLastMonth = (Integer) t.PointsLastMonth__c;
        }

        private String name { get; set; }
        private String rankLastMonth { get; set; }
        private Integer badgesLastMonth { get; set; }
        private Integer pointsLastMonth { get; set; }
    }
}