force-app/main/default/objects/Trailblazer__c/Trailblazer__c.object-meta.xml
<CustomObject>
    <label>Trailblazer</label>
    <nameField>
        <label>Trailblazer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trailblazer__c/fields/Badges__c.field-meta.xml
<CustomField>
    <fullName>Badges__c</fullName>
    <label>Badges</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trailblazer__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TrailblazerTriggerHandler.cls
public with sharing class TrailblazerTriggerHandler {
    public TrailblazerTriggerHandler() {

    }

    public static void triggerHandler() {
        if (Trigger.isAfter && Trigger.isUpdate) {
            for (Trailblazer__c trailblazer : (List<Trailblazer__c>)Trigger.new) {
                Trailblazer__c oldTrailblazer = (Trailblazer__c) Trigger.oldMap.get(trailblazer.Id);

                if (oldTrailblazer.Badges__c != trailblazer.Badges__c || oldTrailblazer.Points__c != trailblazer.Points__c) {
                    notifiSlack(trailblazer, oldTrailblazer);
                }
            }
        }
    }

    private static void notifiSlack(Trailblazer__c trailblazer, Trailblazer__c oldTrailblazer) {
        Integer points = trailblazer.Points__c != null ? Integer.valueOf(trailblazer.Points__c) : 0;
        Integer badges = trailblazer.Badges__c != null ? Integer.valueOf(trailblazer.Badges__c) : 0;
        Integer badgeCount = Integer.valueOf(trailblazer.Badges__c - oldTrailblazer.Badges__c);
        Integer pointsCount = Integer.valueOf(trailblazer.Points__c - oldTrailblazer.Points__c);

        String message = JSON.serialize(new Map<String, String>{
            'text' => '>' + trailblazer.Name + '\n Total Points: `' + points + '`\n Total Badges: `' + badges + '`\n New Points: `' + pointsCount + '`\n New Badges: `' + badgeCount + '`'
        });
        SlackUtil.sendNotificationToSlack(message);
    }
}